baseURL = 'https://tiagovignatti.github.io/resumimos-cvp/'
languageCode = 'pt-br'
title = 'Nós Resumimos: CVP'
theme = "hugo-news"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menus.main]]
#name = "Principal"
#url = "/"
#weight = 10

#[[menus.main]]
#name = "Categorias"
#url = "/categories"
#weight = 20

#[[menus.main]]
#name = "Tags"
#url = "/tags"
#weight = 30